expiration: 3600000

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.foureverinbeta.s3LinkGenerator' to DEBUG.
    com.foureverinbeta.s3LinkGenerator: DEBUG

# Logback's Time Based Rolling Policy - archivedLogFilenamePattern: ./logs/s3LinkGenerator-%d{yyyy-MM-dd}.log.gz
# Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: ./logs/s3LinkGenerator-%d{yyyy-MM-dd}-%i.log.gz
# Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: ./logs/s3LinkGenerator-%i.log.gz

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/s3LinkGenerator.log
      archivedLogFilenamePattern: ./logs/s3LinkGenerator-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB